CREATE SCHEMA IF NOT EXISTS `purbeurre` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `purbeurre`.`categorie` (
  `id` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `purbeurre`.`food` (
  `id` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `description` VARCHAR(400) NULL DEFAULT NULL,
  `id_categorie` SMALLINT(6) UNSIGNED NOT NULL,
  `shops` VARCHAR(200) NULL DEFAULT NULL,
  `date_save` DATETIME NOT NULL,
  `url_page_off` VARCHAR(500) NULL DEFAULT NULL,
  `nutriscore` CHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categorie_id` (`id_categorie` ASC) VISIBLE,
  CONSTRAINT `fk_categorie_id`
    FOREIGN KEY (`id_categorie`)
    REFERENCES `purbeurre`.`categorie` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `purbeurre`.`substitutes` (
  `id` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_produit` SMALLINT(6) UNSIGNED NULL DEFAULT NULL,
  `id_substitute` SMALLINT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `Food_idx` (`id_produit` ASC) VISIBLE,
  CONSTRAINT `Food`
    FOREIGN KEY (`id_produit`)
    REFERENCES `purbeurre`.`food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8;
