SET NAMES utf8;

DROP TABLE IF EXISTS food;

CREATE TABLE food (
  id SMALLINT(6) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  description VARCHAR(400) DEFAULT NULL,
  id_categorie SMALLINT(6) UNSIGNED NOT NULL,
  shops VARCHAR(200) DEFAULT NULL,
  date_save DATETIME NOT NULL,
  url_page_off VARCHAR(500) DEFAULT NULL,
  nutriscore CHAR(1) DEFAULT NULL,
  id_substitutes SMALLINT(6) UNSIGNED NOT NULL
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS categorie;

CREATE TABLE categorie (
  id SMALLINT(6) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL
) 
ENGINE=InnoDB;

DROP TABLE IF EXISTS substitutes;

CREATE TABLE substitutes (
  id SMALLINT(6) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  etat_sub VARCHAR(30) DEFAULT NULL 
) 
ENGINE=InnoDB;

ALTER TABLE food
ADD CONSTRAINT fk_categorie_id FOREIGN KEY (id_categorie) REFERENCES categorie(id);

ALTER TABLE food
ADD CONSTRAINT fk_substitutes_id FOREIGN KEY (id_substitutes) REFERENCES substitutes(id);